#!/bin/bash

# shellcheck disable=2004  ## Inappropriate complaining of "$/${} is unnecessary on arithmetic variables."
# shellcheck disable=2034  ## Unused variables.
# shellcheck disable=2119  ## Disable confusing and inapplicable warning about function's $1 meaning script's $1.
# shellcheck disable=2155  ## Disable check to 'Declare and assign separately to avoid masking return values'.
# shellcheck disable=2120  ## OK with declaring variables that accept arguments, without calling with arguments (this is 'overloading').
# shellcheck disable=2001  ## Complaining about use of sed istead of bash search & replace.
# shellcheck disable=2002  ## Useless use of cat. This works well though and I don't want to break it for the sake of syntax purity.
# shellcheck disable=2317  ## Can't reach
# shellcheck disable=2143  ## Used grep -q instead of echo | grep
# shellcheck disable=2162
# shellcheck disable=2207
# shellcheck disable=2181

##	Purpose: See fPrint_About() below.
##	Notes:
##		- THIS SCRIPT IS MANAGED ON GITHUB.
##		- See bottom of file for examples of numbers in various bases, and the space-saving percentages.
##	Copyright and license .........: Toward bottom of this file.
##	History .......................: At bottom of this file.
##	Evaluation of Unicode chars ...: Near bottom of this file.


## Boilerplate constants (but don't actually make read-only because of errors during script-managed recursion).
declare -i    doDebug=0
declare -i    runAsSudo=0
declare -i    doQuietly=0; [[ "${X9CONVERTBASE1_QUIET}" == "1" ]] && doQuietly=1
declare       thisVersion="1.1.0"
declare       copyrightYear="2023-2026"
declare       author="Jim Collier"


fPrint_About(){
	((doQuietly))  &&  return
	fEcho_Clean ""
	fEcho_Clean "Converts from some bases to a wide variety of others."
	fEcho_Clean ""
}

fPrint_Syntax(){
	((doQuietly))  &&  return
	#           X"-------------------------------------------------------------------------------"X
	fEcho_Clean ""
	fEcho_Clean "Syntax: ${meName}  [optional args]  <NUMBER>  <OBASE>"
	fEcho_Clean "  Required arguments (in any order):"
	fEcho_Clean "    <NUMBER> .........: The value to convert, in form --ibase"
	fEcho_Clean "    <OBASE> ..........: The base to convert to"
	fEcho_Clean "  Optional arguments:"
	fEcho_Clean "    --ibase <base> ...: The input base (assumed to be 10 ifnot specified)"
	fEcho_Clean "    --lcase ..........: Lower case (for bases with alpha and only one case)"
	fEcho_Clean "    --clipin .........: Use clipboard for input"
	fEcho_Clean "    --clipout ........: Use clipboard for output"
	fEcho_Clean "    --silent .........: No CLI output. Also sets --clipout."
	fEcho_Clean "    --help"
	fEcho_Clean "  Valid values for output <base>:"
	fEcho_Clean "    Actual standards:"
	fEcho_Clean "        2 ....: aka Binary ................. 0,1"
	fEcho_Clean "        8 ....: aka Octal .................. 0-7"
	fEcho_Clean "       10 ....: aka Decimal [default] ...... 0-9"
	fEcho_Clean "       16 ....: aka Hexedecimal ............ 0-9, A-F"
	fEcho_Clean "       32[r]..: RFC 4648 ................... A-Z, 2-7" #.......................... https://en.wikipedia.org/wiki/Base32
	fEcho_Clean "       32h ...: RFC 4648 §7, 'Base32Hex' ... 0-9, A-V" #.......................... https://datatracker.ietf.org/doc/html/rfc4648#section-7
	fEcho_Clean "       32w ...: Wordsafe Base32 ............ 2-9, CFGHJMPQRVWX, cfghjmpqrvwx" #... https://en.wikipedia.org/wiki/Base32#Word-safe_alphabet
	fEcho_Clean "       36 ....: Just alphanum .............. 0-9, A-Z" #.......................... https://en.wikipedia.org/wiki/Base36
	fEcho_Clean "       62 ....: All alphanum ............... 0-9, A-Z, a-z" #..................... https://en.wikipedia.org/wiki/Base62
	fEcho_Clean "       64[h] .: Hex like, URL-safe ......... 0-9, A-Z, a-z, -, _" #............... https://en.wikipedia.org/wiki/Base64#Variants_summary_table
	fEcho_Clean "       64r....: RFC 4648 ................... A-Z, a-z, 0-9, +, /" #............... https://en.wikipedia.org/wiki/Base64
	fEcho_Clean "       64u ...: RFC 4648 §5; URL-safe ...... A-Z, a-z, 0-9, -, _" #............... https://en.wikipedia.org/wiki/Base64#Variants_summary_table
	fEcho_Clean "    De-facto standards:"
	fEcho_Clean "       26 ....: One-case alphabetic ........ A-Z"
	fEcho_Clean "       32c ...: Crockford's Base32 ......... 0-9, A-Z no I, L, O, U" #............ https://en.wikipedia.org/wiki/Base32#Crockford's_Base32
	fEcho_Clean "       52 ....: Both-case alphabetic ....... A-Z, a-z"
	fEcho_Clean "    Very slightly custom:"
	fEcho_Clean "       64j1u..: Alternate to 64u but also programmer-friendly"
	fEcho_Clean "    Custom word-safe, URL-safe, filesystem-safe, programmer-friendly:"
	fEcho_Clean "       48j1w..: Base 32w + unicode symbols"
	fEcho_Clean "       64j1w..: Base 48j1w + more unicode symbols"
	fEcho_Clean "      128j1w..: Base 64j1w + more unicode symbols"
	fEcho_Clean "    Custom [not word-safe], URL-safe, filesystem-safe, programmer-friendly:"
	fEcho_Clean "      128j1 ..: Base 62 + unicode symbols"
	fEcho_Clean "      256j1 ..: Base 128j1 + more unicode symbols"
	fEcho_Clean "      288j1 ..: Base 256j1 + more unicode symbols"
	fEcho_Clean "    Special-purpose bases [not very useful for output-only bases]:"
	fEcho_Clean "      38hostname: Valid *nix host and domain name characters"
	fEcho_Clean "      39username: Valid *nix username characters"
	fEcho_Clean "      45email:    Valid email characters"
	fEcho_Clean "  Valid values for --ibase:"
	fEcho_Clean "    2, 8, 10, 16, 36"  ## Note: You might think that base32/base64 might work, but those must be values at 32 or 64-bit boundaries. Maybe they could be padded in a future update?
	fEcho_Clean "Notes:"
	fEcho_Clean "  ▸ Base 32 and 64 are often used for streaming binary-to-text encoding/de-"
	fEcho_Clean "    coding, but there's no reason you can't use them for positional notation."
	fEcho_Clean "  ▸ All bases are human-readable/comparable. But not even RFC standard bases >36"
	fEcho_Clean "    will machine-sort properly with common sort regimes, eg LC_COLLATE=C.UTF-8."
	#           X"-------------------------------------------------------------------------------"X
}

fPrint_Copyright(){
	((doQuietly))  &&  return
	fEcho_Clean ""
	fEcho_Clean "${meName} version ${thisVersion}"
	fEcho_Clean "Copyright (c) ${copyrightYear} ${author}."
	fEcho_Clean "License GPLv3+: GNU GPL version 3 or later, full text at:"
	fEcho_Clean "    https://www.gnu.org/licenses/gpl-3.0.en.html"
	fEcho_Clean "There is no warranty, to the extent permitted by law."
	fEcho_Clean ""
}


fMain(){

	## Pre-validation
	_fMustBeInPath basename
	_fMustBeInPath bc

	## Template constants (this gest run twice if $runAsSudo == 1)
	local    -r doDebug="${doDebug}"  ## Make immutible for rest of script.
	local    -r meName="${meName}"    ## Make immutible for rest of script.

	## Template variables (soon to be constants)
	local -a allArgs=()

	## Standardized bases
	local -ar b2=($(echo {0..1}))
	local -ar b8=($(echo {0..7}))
	local -ar b10=($(echo {0..9}))
	local -ar b16=($(echo {0..9} {A..F}))
	local -ar base32r=($(echo {A..Z} {2..9})) #.............................................. RFC 4648
	local -ar base32h=($(echo {0..9} {A..V})) #.............................................. RFC 4648 hex
	local -ar base32w=(2 3 4 5 6 7 8 9 C F G H J M P Q R V W X c f g h j m p q r v w x) #.... Wordsafe
	local -ar base36=($(echo {0..9} {A..Z})) #............................................... Base36
	local -ar base62=($(echo {0..9} {A..Z} {a..z})) #........................................ Base62
	local -ar base64r=($(echo {A..Z} {a..z} {0..9} "+ /")) #................................. RFC 4648
	local -ar base64u=($(echo {A..Z} {a..z} {0..9} "- _")) #.................................. RFC 4648 url-safe variant

	## De-facto standards
	local -ar base26=($(echo {A..Z}))
	local -ar base32c=(0 1 2 3 4 5 6 7 8 9 A B C D E F G H J K M N P Q R S T V W X Y Z) #.... Crockford; no I, L, O, U; one famous programmer's proposal that has become a more-or-less de-facto accepted standard variant.
	local -ar base52=($(echo {A..Z} {a..z}))
	local -ar base64h=($(echo {0..9} {A..Z} {a..z} "- _")) #.................................. RFC 4648 url-safe variant

	## Very slight custom modifications
	local -ar base64j1=($(echo {0..9} {A..Z} {a..z} "ʞ λ")) #............................... Custom programmer-safe unicode symbol variant

#	## Deprecated: Custom 'word-safe', URL-safe, filesystem-safe, and programmer-friendly variants that strive to be CLI-width-friendly (but may not always render properly in every terminal or program with every font).
#	local -ra base48j1w=(0 1 2 3 4 5 6 7 8 9 c f g h j m p q r v w x ʞ λ μ ᛎ ᛏ ᛘ ᛯ ᛝ ᛦ ᛨ ᚠ ᚧ ᚬ ᚼ 🜣 🜥 🜿 🝅 ▵ ▸ ▿ ◂ ҂ ‡ ± ⁑)
#	local -ra base64j1w=(0 1 2 3 4 5 6 7 8 9 C F G H J M P Q R V W X c f g h j m p q r v w x ʞ λ μ ᛎ ᛏ ᛘ ᛯ ᛝ ᛦ ᛨ ᚠ ᚧ ᚬ ᚼ 🜣 🜥 🜿 🝅 ▵ ▸ ▿ ◂ ҂ ‡ ± ⁑ ÷ ∞ ≈ ≠)
#	local -ra base128j1w=(0 1 2 3 4 5 6 7 8 9 C F G H J M P Q R V W X c f g h j m p q r v w x ʞ λ μ ᛎ ᛏ ᛘ ᛯ ᛝ ᛦ ᛨ ᚠ ᚧ ᚬ ᚼ 🜣 🜥 🜿 🝅 ▵ ▸ ▿ ◂ ҂ ‡ ± ⁑ ÷ ∞ ≈ ≠ Ω Ʊ Ξ ψ Ϡ δ ϟ Ћ Ж Я Ѣ ф ¢ £ ¥ § ¿ ɤ ʬ ⍤ ⍩ ⌲ ⍋ ⍒ ⍢ Â Ĉ Ê Ĝ Ĥ Ĵ Ŝ Ŵ Ŷ â ĉ ê ĝ ĥ ĵ ŝ ŵ ŷ Ã Ẽ Ñ Ỹ ã ẽ ñ ỹ Ä Ë Ẅ Ẍ Ÿ ä ë ẅ ẍ ÿ Á Ć É)

	## Custom 'word-safe', URL-safe, filesystem-safe, and programmer-friendly variants that strive to be CLI-width-friendly (but may not always render properly in every terminal or program with every font).
	local -ra base48j1w=(2 3 4 5 6 7 8 9 C F G H J M P Q R V W X c f g h j m p q r v w x ʞ λ μ ᛎ ᛏ ᛘ ᛯ ᛝ ᛦ ᛨ ᚠ ᚧ ᚬ ᚼ 🜣 🜥)
	local -ra base64j1w=(2 3 4 5 6 7 8 9 C F G H J M P Q R V W X c f g h j m p q r v w x ʞ λ μ ᛎ ᛏ ᛘ ᛯ ᛝ ᛦ ᛨ ᚠ ᚧ ᚬ ᚼ 🜣 🜥 🜿 🝅 ▵ ▸ ▿ ◂ ҂ ‡ ± ⁑ ÷ ∞ ≈ ≠ Ω Ʊ)
	local -ra base128j1w=(2 3 4 5 6 7 8 9 C F G H J M P Q R V W X c f g h j m p q r v w x ʞ λ μ ᛎ ᛏ ᛘ ᛯ ᛝ ᛦ ᛨ ᚠ ᚧ ᚬ ᚼ 🜣 🜥 🜿 🝅 ▵ ▸ ▿ ◂ ҂ ‡ ± ⁑ ÷ ∞ ≈ ≠ Ω Ʊ Ξ ψ Ϡ δ ϟ Ћ Ж Я Ѣ ф ¢ £ ¥ § ¿ ɤ ʬ ⍤ ⍩ ⌲ ⍋ ⍒ ⍢ Â Ĉ Ê Ĝ Ĥ Î Ĵ Ô Ŝ Û Ŵ Ŷ Ẑ â ĉ ê ĝ ĥ î ĵ ô ŝ û ŵ ŷ ẑ Ã Ẽ Ĩ Ñ Õ Ũ Ỹ ã ẽ ĩ ñ õ ũ ỹ Ä)

	## Custom (not 'word-safe'), URL-safe, filesystem-safe, and programmer-friendly variants that strive to be CLI-width-friendly (but may not always render properly in every terminal or program with every font).
	local -ra base128j1=(0 1 2 3 4 5 6 7 8 9 A B C D E F G H I J K L M N O P Q R S T U V W X Y Z a b c d e f g h i j k l m n o p q r s t u v w x y z ʞ λ μ ᛎ ᛏ ᛘ ᛯ ᛝ ᛦ ᛨ ᚠ ᚧ ᚬ ᚼ 🜣 🜥 🜿 🝅 ▵ ▸ ▿ ◂ ҂ ‡ ± ⁑ ÷ ∞ ≈ ≠ Ω Ʊ Ξ ψ Ϡ δ ϟ Ћ Ж Я Ѣ ф ¢ £ ¥ § ¿ ɤ ʬ ⍤ ⍩ ⌲ ⍋ ⍒ ⍢ Â Ĉ Ê Ĝ Ĥ Î Ĵ Ô Ŝ Û Ŵ)
	local -ra base256j1=(0 1 2 3 4 5 6 7 8 9 A B C D E F G H I J K L M N O P Q R S T U V W X Y Z a b c d e f g h i j k l m n o p q r s t u v w x y z ʞ λ μ ᛎ ᛏ ᛘ ᛯ ᛝ ᛦ ᛨ ᚠ ᚧ ᚬ ᚼ 🜣 🜥 🜿 🝅 ▵ ▸ ▿ ◂ ҂ ‡ ± ⁑ ÷ ∞ ≈ ≠ Ω Ʊ Ξ ψ Ϡ δ ϟ Ћ Ж Я Ѣ ф ¢ £ ¥ § ¿ ɤ ʬ ⍤ ⍩ ⌲ ⍋ ⍒ ⍢ Â Ĉ Ê Ĝ Ĥ Î Ĵ Ô Ŝ Û Ŵ Ŷ Ẑ â ĉ ê ĝ ĥ î ĵ ô ŝ û ŵ ŷ ẑ Ã Ẽ Ĩ Ñ Õ Ũ Ỹ ã ẽ ĩ ñ õ ũ ỹ Ä Ë Ï Ö Ü Ẅ Ẍ Ÿ ä ë ï ö ü ẅ ẍ ÿ Á Ć É Ǵ Í Ń Ó Ŕ Ś Ú Ẃ Ý Ź á ć é ǵ í ń ó ŕ ś ú ẃ ý ź Ā Ē Ī Ō Ū Ȳ ā ē ī ō ū ȳ Ǎ Č Ď Ě Ǧ Ȟ Ǩ Ň Ǒ Ř Š Ǔ ǎ č ď ě ǧ ȟ ǩ ň ǒ ř š ǔ ǝ ɹ ʇ ʌ ₸ ᛬ 웃 유 ㅈ ㅊ ㅍ ㅎ ㅱ ㅸ ㅠ ソ ッ ゞ ぅ ぇ ォ)
	local -ra base288j1=(0 1 2 3 4 5 6 7 8 9 A B C D E F G H I J K L M N O P Q R S T U V W X Y Z a b c d e f g h i j k l m n o p q r s t u v w x y z ʞ λ μ ᛎ ᛏ ᛘ ᛯ ᛝ ᛦ ᛨ ᚠ ᚧ ᚬ ᚼ 🜣 🜥 🜿 🝅 ▵ ▸ ▿ ◂ ҂ ‡ ± ⁑ ÷ ∞ ≈ ≠ Ω Ʊ Ξ ψ Ϡ δ ϟ Ћ Ж Я Ѣ ф ¢ £ ¥ § ¿ ɤ ʬ ⍤ ⍩ ⌲ ⍋ ⍒ ⍢ Â Ĉ Ê Ĝ Ĥ Î Ĵ Ô Ŝ Û Ŵ Ŷ Ẑ â ĉ ê ĝ ĥ î ĵ ô ŝ û ŵ ŷ ẑ Ã Ẽ Ĩ Ñ Õ Ũ Ỹ ã ẽ ĩ ñ õ ũ ỹ Ä Ë Ï Ö Ü Ẅ Ẍ Ÿ ä ë ï ö ü ẅ ẍ ÿ Á Ć É Ǵ Í Ń Ó Ŕ Ś Ú Ẃ Ý Ź á ć é ǵ í ń ó ŕ ś ú ẃ ý ź Ā Ē Ī Ō Ū Ȳ ā ē ī ō ū ȳ Ǎ Č Ď Ě Ǧ Ȟ Ǩ Ň Ǒ Ř Š Ǔ ǎ č ď ě ǧ ȟ ǩ ň ǒ ř š ǔ ǝ ɹ ʇ ʌ ₸ ᛬ 웃 유 ㅈ ㅊ ㅍ ㅎ ㅱ ㅸ ㅠ ソ ッ ゞ ぅ ぇ ォ ゲ サ じ す ス せ ち づ で ネ ビ べ ぺ ま モ ゟ ヲ ½ ⅓ ⅔ ¼ ¾ ⅕ ⅖ ⅗ ⅘ ⅙ ⅚ ⅛ ⅜ ⅝ ⅞)

	## Custom; Special: ^[a-z_]([a-z0-9_-]){0,31}$; linux hostname (including domain - not case-sensitive, usually lower-case, and this is just the legal chars): [0-9a-z\-\.]
	declare -a base38hostname=($(echo {0..9} {a..z} "- ."))
	declare -a base39username=($(echo {0..9} {a..z} "- _ ."))

		## Args (1] Define placeholder variables; 2] Call fInit() to set them; 3] Freeze them read-only.)
	local    arg_inputVal=""
	local    arg_inBase=""
	local    arg_outBase=""
	local    inputVal=""
	local    inBase=""
	local    outBase=""
	local -i doLowerCase=0
	local -i doUseClipIn=0
	local -i doUseClipOut=0
	local -i doSilent=0
	fInit "${1}" "${2}" "${3}" "${4}" "${5}" "${6}" "${7}" "${8}" "${9}" "${10}" "${11}" "${12}" "${13}" "${14}" "${15}" "${16}" "${17}" "${18}" "${19}" "${20}" "${21}" "${22}" "${23}" "${24}" "${25}" "${26}" "${27}" "${28}" "${29}" "${30}" "${31}" "${32}"

	## Defaults
	[[ -z "${inBase}" ]] && inBase="10"
	[[ "${inBase}" != "10" ]] && [[ -z "${outBase}" ]] && outBase="10"
	((doSilent)) && doUseClipOut=1  ## If you use --silent without --clipout, nothing happens.

	## Get $inputVal from clipboard if appropriate
	if ((doUseClipIn)); then
		[[ -z "$(which xclip 2>/dev/null || true)" ]] && fThrowError "Can't get value from clipboard because 'xclip' is not installed."  "${FUNCNAME[0]}"
		inputVal="$(xclip -o -selection clipboard)"
	fi

	## Validate everything
	fValidate

	## Lock variables down that we can
	local -ra allArgs=("${allArgs[@]}")
	local -r arg_inputVal="${arg_inputVal}"
	local -r arg_inBase="${arg_inBase}"
	local -r arg_outBase="${arg_outBase}"
	local -r  inputVal="${inputVal}"
#	local -r  inBase="${inBase}"  ## Can't lock this yet
	local -r  outBase="${outBase}"
	local -ri doLowerCase=$doLowerCase
	local -ri doUseClipIn=$doUseClipIn
	local -ri doUseClipOut=$doUseClipOut
	local -ri doSilent=$doSilent

	#DEBUG
	#echo "\${allArgs[*]} = ${allArgs[*]}"
	#echo "Arg count = ${#allArgs[@]}"
	#fEchoVarAndVal arg_inputVal
	#fEchoVarAndVal arg_inBase
	#fEchoVarAndVal arg_outBase
	#fEchoVarAndVal inputVal
	#fEchoVarAndVal inBase
	#fEchoVarAndVal outBase
	#fEchoVarAndVal doLowerCase
	#fEchoVarAndVal doUseClipIn
	#fEchoVarAndVal doUseClipOut
	#fEchoVarAndVal doSilent
	#echo
	#exit

	##
	## Make it so
	##

	## Environment varibles
	export BC_LINE_LENGTH=0

	## Convert ${inputVal} to base10 if necessary
	local inputVal_base10=0
	case "${inBase}" in
		"2"|"8"|"16"|"26"|"36")
			## As we've already validated, bc can only go up to base 36.
			inputVal_base10="$(bc <<< "ibase=${inBase}; ${inputVal}")"
			inBase="10"
			;;
		"10")
			## Already base10
			inputVal_base10=${inputVal}
	esac
	local -r inBase="${inBase}"

	## Set obase for bc (for OUTput base); just an integer.
	bcObase=$(echo "${outBase}" | grep -iPo "[0-9]+" | head -n 1)

	## Check if output should also be base 10, in which case we're done.
	if [[ $bcObase -eq 10 ]]; then
		## User wants output in base 10, so we're done.
		fShowOutput "${inputVal_base10}"
		return
	fi

	## Convert ${inputVal_base10} input to ${bcObase}, which may output an array of digits if number as large and obase>16.
	local bcOutputDigitArray=""
	bcOutputDigitArray="$(bc <<< "obase=${bcObase}; ${inputVal_base10}")"

	## Validate; error if output has spaces, AND base <= 16 (which shouldn't be possible)
	[[ -n "$(echo "${bcOutputDigitArray}" | grep -iP "\ " )" ]] && [[ $bcObase -le 16 ]] && fThrowError "Unexpected error. 'bc' seems to have output an array, but base of ${bcObase} is <=16. 'bc' output: '${bcOutputDigitArray}'."  "${FUNCNAME[0]}"

	## If base is less than 16, it won't need any more work
	if [[ $bcObase -le 16 ]]; then
		fShowOutput "${bcOutputDigitArray}"
		return
	fi

	##
	## Substitute 'bc' output numbers with base characters
	##

	## Populate base character array
	case "${outBase}" in
		"26")           local -ar baseValArray=("${base26[@]}")          ;;
		"32"|"32r"*)    local -ar baseValArray=("${base32r[@]}")         ;;
		"32h"*)         local -ar baseValArray=("${base32h[@]}")         ;;
		"32c"*)         local -ar baseValArray=("${base32c[@]}")         ;;
		"32w"*)         local -ar baseValArray=("${base32w[@]}")         ;;
		"36")           local -ar baseValArray=("${base36[@]}")          ;;
		"38ho"*)        local -ar baseValArray=("${base38hostname[@]}")  ;;
		"39us"*)        local -ar baseValArray=("${base39username[@]}")  ;;
		"48j1w")        local -ar baseValArray=("${base48j1w[@]}")       ;;
		"52")           local -ar baseValArray=("${base52[@]}")          ;;
		"62")           local -ar baseValArray=("${base62[@]}")          ;;
		"64"|"64r"*)    local -ar baseValArray=("${base64r[@]}")         ;;
		"64u"*)         local -ar baseValArray=("${base64u[@]}")         ;;
		"64j1"|"64j1u") local -ar baseValArray=("${base64j1[@]}")       ;;
		"64j1w")        local -ar baseValArray=("${base64j1w[@]}")       ;;
		"128j1w")       local -ar baseValArray=("${base128j1w[@]}")      ;;
		"256j1")        local -ar baseValArray=("${base256j1[@]}")       ;;
		"288j1")        local -ar baseValArray=("${base288j1[@]}")       ;;
	esac

	local -i index
	for item in $(bc <<< "obase=${bcObase}; ${inputVal_base10}"); do
		index=$((10#$item))  ## Leading 0s get interpreted by bash as octal, so convert to base10 and strip off leading 0s
		retVal="${retVal}${baseValArray[${index}]}"
	done

	fShowOutput "${retVal}"
	return

}


fShowOutput(){

	local inputStr="$1"

	#DEBUG
	#fEchoVarAndVal doLowerCase

	## Lower case if desired and valid
	((doLowerCase)) && inputStr="${inputStr,,}"
	local -r inputStr="${inputStr}"

	if ((! doSilent)); then
		echo "${inputStr}"
	fi
	if ((doUseClipOut)); then
		echo -n "${inputStr}" | xclip -selection clipboard
	fi

}


fInit(){

	## Constants
	local -r _allArgs="$*"

	## Positional variables set (to not rely on detecting empty strings, which may themselves be valid settings)
	local -i argIsSet_InputVal=0

	## Determine if we need to show help
	case " ${_allArgs,,} " in
		*" -h "*|*" --help "*)                 fPrint_Copyright ; fPrint_About ; fPrint_Syntax ; exit 0 ;;
		*" -v "*|*" --ver "*|*" --version "*)  fPrint_Copyright ; fPrint_About                 ; exit 0 ;;
	esac
	if [[ -z "$(_fStrTrim_byecho "${_allArgs}")" ]]; then fPrint_Copyright; fPrint_About; fPrint_Syntax; exit 1; fi

	## Populate args array in a way that it stops at last non-empty value [GENERIC]
	local -i highestNonEmpty=0
	for ((i=1; i<=32; i++))              ; do  [[ -n "${!i}" ]] && highestNonEmpty=$i ; done
	for ((i=1; i<=highestNonEmpty; i++)) ; do  allArgs+=("${!i}")                     ; done
	unset highestNonEmpty

	## Init for loop
	local    tmpStr=""
	local    currentArg=""
	local    lastSwitch=""
	local -i expectingSwitchParamForNextArg=0
	local -i wasLastArg=0
	local -i emptyArgCount=0

	## Process arguments
	for currentArg in "${allArgs[@]}"; do
		#fEcho "fInin(): currentArg='${currentArg}' (start of loop)"  #DEBUG

		## Test if an option switch or not
		if [[ ${currentArg} == -* && ${currentArg} != *" "* && ${currentArg} != - ]]; then
			#fEcho "fInin(): currentArg='${currentArg}' (option switch)"  #DEBUG
			## It's an option switch

			## Check if this was supposed to NOT be a switch (eg expecting a parameter after previous switch)
			((${expectingSwitchParamForNextArg})) && fThrowError "Expecting a non-switch argument for '${lastSwitch}', instead got '${currentArg}'."  "${FUNCNAME[0]}"

			## Validate switches, and act on unary switches
			tmpStr="${currentArg,,}"  ## Lower case
			while [[ $tmpStr == -* ]]; do tmpStr="${tmpStr#-}"; done  ## Strip dashes off
			lastSwitch="${tmpStr}"    ## Remember lastSwitch
			case "${tmpStr}" in

				## Unitary switches (that take no extra params); Comment this test out if this script accepts no such thing.
				"lc"*|*"case"|"lower"*)          doLowerCase=1  ;;
				"clip"*"in"|"ic"*)               doUseClipIn=1  ;;
				"clip"*"out"|"oc"*)              doUseClipOut=1 ;;
				"silent")                        doSilent=1     ;;

				## Everything else, expecting a non-switch for next argument
				"ib"*|"inb"*|"in-b"*|"bi"*|"basei"*|"base-i"*)	expectingSwitchParamForNextArg=1 ;;

				"") : ;;  ## Special case of user passing bare "--". Usually means "end of arg processing", but ignore for now.

				## ¯\_(ツ)_/¯
				*)  fThrowError  "Argument invalid or not expected in this context: '${currentArg}'."  "${FUNCNAME[0]}" ;;

			esac

		else
			## It's not an option switch; could be an option switch param, or a positional arg

			if ((expectingSwitchParamForNextArg)); then
				## Expecting option switch param

				case "${lastSwitch,,}" in
					"ib"*|"inb"*|"in-b"*|"bi"*|"basei"*|"base-i"*)  arg_inBase="${currentArg}"      ;;
					*)                                              fThrowError "Unkown parameters. Switch: '--${lastSwitch}', current parameter: '${currentArg}'."  "${FUNCNAME[0]}" ;;
				esac
				expectingSwitchParamForNextArg=0

			else
				## Well it must be a positional arg then.

				if ((! argIsSet_InputVal)) && (( ! doUseClipIn)); then
					inputVal="${currentArg}"
					argIsSet_InputVal=1
				elif ((! argIsSet_arg_outBase)); then
					arg_outBase="${currentArg}"
					argIsSet_arg_outBase=1
				elif [[ -n "${currentArg}" ]]; then
					fThrowError "Unexpected positional argument: '${currentArg}'."  "${FUNCNAME[0]}"
				else
					fThrowError "Unknown error. Current arg: '${currentArg}'."  "${FUNCNAME[0]}"
				fi

			fi

		fi

		(($wasLastArg)) && break
	done

	## Validate
	((expectingSwitchParamForNextArg)) && fThrowError "Never received a parameter for switch '--${lastSwitch}'."

	## Normalize base names
	inBase="${arg_inBase}"
	outBase="${arg_outBase}"
	fNormalizeBaseName_byRef inBase
	fNormalizeBaseName_byRef outBase

}


fValidate(){

	## Validate
	[[ -z "${inputVal}" ]] && fThrowError "An input value must be specified."  "${FUNCNAME[0]}"
	[[ -z "${outBase}" ]] && fThrowError "An output base must be specified."  "${FUNCNAME[0]}"
#	[[ -z "$(echo "x ${outBase} x" | grep -iP "x (2|8|10|16|26|32([rhcw].*)?|36|38(us|ho).*|48j1?|52|62|64((r|u|j1u|j1uw).*)?|94(as.*)?|(128|256|288)(j1)?) x" || true)" ]] && fThrowError "Sorry, --obase of '${arg_outBase}' is not supported."  "${FUNCNAME[0]}"
	[[ -z "$(echo "x ${outBase} x" | grep -iP "x (2|8|10|16|26|32|32(c|h|r|w)|36|38ho.*|39us.*|45em.*|48j1w|52|62|64|64(h|r|u)|64j1(u|w)|128j1|128j1w|256j1|288j1) x" || true)" ]] && fThrowError "Sorry, --obase of '${arg_outBase}' is not supported."  "${FUNCNAME[0]}"


	## Validate; make sure input characters all exist in input base
	local validBaseChars=""
	case "${inBase}" in
		"2")   validBaseChars="${b2[*]}"      ;;
		"8")   validBaseChars="${b8[*]}"      ;;
		"10")  validBaseChars="${b10[*]}"     ;;
		"16")  validBaseChars="${b16[*]}"     ;;
		"26")  validBaseChars="${base26[*]}"  ;;
		"36")  validBaseChars="${base36[*]}"  ;;
		*)     fThrowError "Sorry, --ibase of '${arg_inBase}' is not currently supported."  "${FUNCNAME[0]}" ;;
	esac
	local -r validBaseChars="${validBaseChars//" "/""}"  ## Strip out spaces
	local -r replaceWithChar="#"  ## 'Յ' = Armenian U+0545 and should never be used as a base char because it looks like ascii '3', but tr has problems with it.
	local -r testStr="$(tr -s "${validBaseChars}" "${replaceWithChar}" <<< "${inputVal}")"
	if [[ "${testStr}" != "${replaceWithChar}" ]]; then
		fThrowError "The input value of '${inputVal}' has characters outside the base array of '${validBaseChars}'."  "${FUNCNAME[0]}"
	fi

	## Validate lower case if desired and valid
	## UDPATE: Don't error if invalid in context, as the cognitive load on the user is too high; just benevolently fix the flag and move on.
	if ((doLowerCase)); then
		case "${outBase}" in
		#	"32w"*|"52"|"62"|"64"*|"94"*|"128"*)        fThrowError "The switch '--lcase' is incompatible with mixed-case base of ${arg_outBase}."  "${FUNCNAME[0]}" ;;
			"16"|"26"|"32"|"32r"*|"32h"*|"32c"*|"36")   : ;; ## The switch is valid.
			*)                                          doLowerCase=0 ;;  ## There are no upper-case chars anyway, so just disable the switch and don't complain.
		esac
	fi

}


fNormalizeBaseName_byRef(){
	local varName="$1"
	local varVal="${!varName}"

	## Base names to numbers
	case "${varVal,,}" in
		"bin"*) varVal="2"  ;;
		"oct"*) varVal="8"  ;;
		"dec"*) varVal="10" ;;
		"hex"*) varVal="16" ;;
	esac

	## Strip "b" or "base" off
	if   [[ -n "$(echo "${varVal}"  | grep -iP "base[0-9]+.*")" ]]; then varVal="${varVal/"base"/""}"
	elif [[ -n "$(echo "${varVal}"  | grep -iP "b[0-9]+.*")"    ]]; then varVal="${varVal/"b"/""}"; fi

	## Return
	eval "${varName}='${varVal}'"

}


fPromptToContinue(){
	local answer=""
	fEcho_Clean ""
	read -r -p "Continue? (y/n): " answer
	if [[ "${answer,,}" != "y" ]]; then
		fEcho "User aborted."
		exit 0
	fi
	fEcho_ResetBlankCounter
}


fCleanup(){ :
#	((! doSkipIntroStuff)) && ((! doQuietly)) && fEcho_Clean
}




##
##	Generic library
##	Purpose:
##		- Provide "library" functions to new scripts. But in a way that can be easily shared as single-script solutions.
##			- The old method of sourcing a '0_library_vN', while cleaner in terms of maintaining a whole library of scripts,
##			  made publishing/sharing more difficult. It's the classic tradeoff. But now that this code is extremely stable,
##			  it makes sense to be more publish & single-script frienly, and live with the downsides of such redundancy.

function _fStrTrim_byecho(){
	##	Purpose: Strip off leading and trailing whitespace from a string.
	##	Input:
	##		1 [REQUIRED]: String to trim.
	##	Returns:
	##		Modified string via echo. Capture with: MyVariable="$(_MyFunction "MyArg1" ...etc...)"
	##	History:
	##		- 20190826 JC: Created by copying from 0_library_v2.
	##		- 20190920 JC: Improved function header comments.
	local inputStr="$*"
	if [[ -n "${inputStr}" ]]; then
		outputStr="$(echo -e "${inputStr}" | sed 's/^[[:blank:]]*//;s/[[:blank:]]*$//' 2>/dev/null || true)"
	fi
	echo -n "${outputStr}"
}

function _fMustBeInPath(){
	##	History:
	##		- 20190826 JC: Created by copying from 0_library_v2.
	local -r programToCheckForInPath="$1"
	if [[ -z "${programToCheckForInPath}" ]]; then
		fThrowError "_fMustBeInPath(): Not program specified."
	elif [[ -z "$(command -v "${programToCheckForInPath}" 2>/dev/null || true)" ]]; then
		fThrowError "Not found in path: ${programToCheckForInPath}"
	fi
}


##
##	Generic echo-related stuff. (Minified.)
##
declare -i _wasLastEchoBlank=0
fEcho_Clean(){
	if [[ -n "${1}" ]]                  ; then  echo -e "${1}" ; _wasLastEchoBlank=0
	elif [[ $_wasLastEchoBlank -eq 0 ]] ; then  echo           ; _wasLastEchoBlank=1
	fi; }
# shellcheck disable=2120  ## References arguments, but none are ever passed; Just because this library function isn't called here, doesn't mean it never will in other scripts.
fEcho()                   { if [[ -n "$*" ]]; then fEcho_Clean "[ $* ]"; else fEcho_Clean ""; fi; }
fEcho_Force()             { fEcho_ResetBlankCounter; fEcho "$*";                                  }
fEcho_Clean_Force()       { fEcho_ResetBlankCounter; fEcho_Clean "$*";                            }
fEchoVarAndVal()          { fEcho_Clean "${2}${1} = '${!1}'";                                     }
fEcho_ResetBlankCounter() { _wasLastEchoBlank=0;                                                  }


##
##	Generic error-handling  stuff. (Minified.)
##	History
##		- 20190826 JC: Created by copying from 0_library_v2.
##		- 20190919 JC: Slight tweaks to improve newline output.

declare -i _wasCleanupRun=0
fThrowError(){
	local errMsg="$1"
	local funcName="$2"
	[[ -z "${errMsg}" ]] && errMsg="An error occurred."
	if [[ -z "${errMsg}" ]]; then
		errMsg="${meName}: ${errMsg}"
	else
		errMsg="${meName}.$2(): ${errMsg}"
	fi
	fEcho_Clean
	fEcho_Clean "${errMsg}"
	fEcho_Clean
	exit 1 ; }
function _fTrap_Exit(){
	[[ "${_wasCleanupRun}" != "0" ]] && return
	_wasCleanupRun=1
	_fSingleExitPoint "${1}" "${2}" "${3}" "${4}" "${5}" "${6}" "${7}" "${8}" "${9}" "${10}" "${11}" "${12}" "${13}" "${14}" "${15}" "${16}" "${17}" "${18}" "${19}" "${20}" "${21}" "${22}" "${23}" "${24}" "${25}" "${26}" "${27}" "${28}" "${29}" "${30}" "${31}" "${32}" ; }
function _fTrap_Error(){
	[[ "${_wasCleanupRun}" != "0" ]] && return
	_wasCleanupRun=1
	fEcho_ResetBlankCounter
	_fSingleExitPoint "${1}" "${2}" "${3}" "${4}" "${5}" "${6}" "${7}" "${8}" "${9}" "${10}" "${11}" "${12}" "${13}" "${14}" "${15}" "${16}" "${17}" "${18}" "${19}" "${20}" "${21}" "${22}" "${23}" "${24}" "${25}" "${26}" "${27}" "${28}" "${29}" "${30}" "${31}" "${32}" ; }
function _fTrap_Error_Ignore(){ true; }
function _fSingleExitPoint(){
	local -r signal="$1";  shift || true
	local -r lineNum="$1"; shift || true
	local -r errNum="$1";  shift || true
	local -r errMsg="$*"
	if [[ "${signal}" == "INT" ]]; then
		fEcho_Force
		fEcho "User interrupted."
		fCleanup  ## User cleanup
		exit 1
	elif [[ "${errNum}" != "0" ]] && [[ "${errNum}" != "1" ]]; then  ## Clunky string compare is less likely to fail than integer
		fEcho_Clean
		fEcho_Clean "Signal .....: '${signal}'"
		fEcho_Clean "Err# .......: '${errNum}'"
		fEcho_Clean "Error ......: '${errMsg}'"
		fEcho_Clean "At line# ...: '${lineNum}'"
		fEcho_Clean
		fCleanup  ## User cleanup
	else
		fCleanup  ## User cleanup
	fi; }
fDefineTrap_Error_Fatal(){ true; trap '_fTrap_Error ERR     ${LINENO} $? $_' ERR ; set -e; }
fDefineTrap_Error_Ignore(){      trap '_fTrap_Error_Ignore' ERR                  ; set +e; }


##
## Execution entry point
##

## Bash settings
set -e
set -E

## Error handling
fDefineTrap_Error_Fatal
trap '_fTrap_Error SIGHUP  ${LINENO} $? $_' SIGHUP
trap '_fTrap_Error SIGINT  ${LINENO} $? $_' SIGINT    ## CTRL+C
trap '_fTrap_Error SIGTERM ${LINENO} $? $_' SIGTERM
trap '_fTrap_Exit  EXIT    ${LINENO} $? $_' EXIT
trap '_fTrap_Exit  INT     ${LINENO} $? $_' INT
trap '_fTrap_Exit  TERM    ${LINENO} $? $_' TERM

## Common constants
declare    meName="$(basename "${BASH_SOURCE[0]}")"

## Main entry point
fMain "${1}" "${2}" "${3}" "${4}" "${5}" "${6}" "${7}" "${8}" "${9}" "${10}" "${11}" "${12}" "${13}" "${14}" "${15}" "${16}" "${17}" "${18}" "${19}" "${20}" "${21}" "${22}" "${23}" "${24}" "${25}" "${26}" "${27}" "${28}" "${29}" "${30}" "${31}" "${32}"


##
## Examples
##

##	A big random base 10 number '2023090613425900000000000000001' in various bases:
##	                      Reduction
##	   Base         Chars  Inc Orig  Number
##		  2           101            11001100010001111010101010101001101101001000111010011010010010010001000110101111111100000000000000001
##		  8            34  66%       3142172525155107232222106577400001
##		 10            31   9%       2023090613425900000000000000001
##		 16            26  16%       1988F5553691D3492235FE0001
##		 26            22  15%       DXNNAGDDUWPNKQIDYGEAMJ
##		 32[r]         21   5%       BTCHVKU3JDU2JEI274AAB
##		 32h           21   -        1J27LAKR93KQ948QVS001
##		 32c           21   -        1K27NAMV93MT948TZW001
##		 32w           21   -        3X49fGcqF5cpF6Cpxr223
##		 36            20   5%       5G53VAIZAJBZ2D5Y2Y9T
##		 48j1          19   5%       153ᚼᛦ🜥⁑h҂▵ᛦ🜿▿▸▿2q🜥q
##		 52            18   5%       NftxKBqjrhTdQKHAGJ
##		 62            17   6%       gR7BplOIkweh9aKht
##		 64[r]         17   -        PYFLLDf7JII8r/W01
##		 64u           17   -        PYFLLDf7JII8r_W01
##		 64j1u         17   -        PYFLLDf7JII8rʞW01
##		 64j1w         17   -        hλMXXHᛝ7VRR8▸≠w01
##		 94[ascii]     16   6%       %+(A}'O^UwzN_{sS
##		128j1w         15   6%       6🜥Mᛦ⍩ÑQŵʬμʞᚼä01
##		256j1          13  13%       Pĵㅍ‡sĨǍᚧYrぇ01
##		288j1          13   0        6zф⅖ẄÃЋゲㅎぇúkᛎ
##
##	Or comparing % only by powers of 2:
##	                      Reduction
##	   Base         Chars  Inc Orig  Number
##		  2           101            11001100010001111010101010101001101101001000111010011010010010010001000110101111111100000000000000001
##		  8            34  66%  66%  3142172525155107232222106577400001
##		 16            26  24%  74%  1988F5553691D3492235FE0001
##		 32[r]         21  19%  79%  BTCHVKU3JDU2JEI274AAB
##		 64[r]         17  19%  83%  PYFLLDf7JII8r/W01
##		128j1w        15  12%  85%  6🜥Mᛦ⍩ÑQŵʬμʞᚼä01
##		256j1        13  13%  87%  Pĵㅍ‡sĨǍᚧYrぇ01
##
##	A date serial in the form YYYMMDDHHMMS (no millenium or one-second precision), "023090617142":
##		  2            35  10101100000010011101101101100110110
##		  8            12  254023555466
##		 10            11  23090617142
##		 16             9  5604EDB36
##		 26             8  CWTLEJRI
##		 32[r]          7  vqe5wzw
##		 32h            7  lg4tmpm
##		 32c            7  ng4xpsp
##		 32w            7  fR6vgmg
##		 36             7  alvk27q
##		 48j1           7  1▿ᛝ🝅1f🜿
##		 52             7  BImDpVi
##		 62             6  PCfsKk
##		 64(r|u|j1u)    6  LWJjis
##		 64j1w         6  XwVᚧᚠ▿
##		 94[ascii]      6  #-fK54
##		128j1w         5  ⍋2⁑▿▿
##		256j1         5  5Ϡ🜿Ǒs
##		288j1         5  3ѢŔ9⅕


##
## Copyright, license, and history
##

##	Copyright
##		Copyright © 2022-2026 Jim Collier (ID: 1cv◂‡Vᛦ)
##		Licensed under the GNU General Public License v2.0 or later. Full text at:
##			https://spdx.org/licenses/GPL-2.0-or-later.html
##		SPDX-License-Identifier: GPL-2.0-or-later
##			Preamble:
##				This program is free software: you can redistribute it and/or modify
##				it under the terms of the GNU General Public License as published by
##				the Free Software Foundation, either version 2 of the License, or
##				(at your option) any later version.
##
##				This program is distributed in the hope that it will be useful,
##				but WITHOUT ANY WARRANTY; without even the implied warranty of
##				MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
##				GNU General Public License for more details.
##
##				You should have received a copy of the GNU General Public License
##				along with this program.  If not, see <https://www.gnu.org/licenses/>.


##	Evaluation of Unicode characters, and what fits on fixed-widh output:
##		OK
##			Standard [safe] ...........: [none]
##			Extended latin ............: ¢£¥§±µ¿÷Ʊɤʬ                     Too wide, ambiguous, or ugly: ©®¶·ºðƍẟɸɷʊʭ
##				circumflex ............: ÂĈÊĜĤÎĴÔŜÛŴŶẐâĉêĝĥîĵôŝûŵŷẑ
##				tilde .................: ÃẼĨÑÕŨỸãẽĩñõũỹ
##				diaeresis .............: ÄËÏÖÜẄẌŸäëḧïöẗüẅẍÿ              Too wide, ambiguous, or ugly: Ḧ
##				diaeresis and macron ..: ǟȫǖ
##				acute .................: ÁĆÉǴÍĹŃÓŔŚÚẂÝŹáćéǵíḱĺńóŕśúẃýź   Too wide, ambiguous, or ugly: ḰḾḿ
##				doulbe acute ..........: ŐőŰű
##				macron ................: ĀĪĒŌŪȲāēḡīōūȳ                   Too wide, ambiguous, or ugly: Ḡ
##				caron .................: ǍČĎĚǦȞǏǨĽŇǑŘŠŤǓǎčďěǧȟǐǩǰľňǒřšťǔ
##				stroke ................: ȺɃȻĐɆĦƗɈľɌŦɎƀȼɇđħɨɉłɍŧɏ
##				hook ..................: Ƒƒ
##				middle tilde ..........: Ɵɫ
##				bar ...................: ʉ
##				In order desired usage.: ¢£¥§±µ¿÷ƱɤʬÂĈÊĜĤĴŜŴŶâĉêĝĥĵŝŵŷÃẼÑỸãẽñỹÄËẄẌŸäëẅẍÿÁĆÉǴŃŔẂÝáćéǵńŕẃýǍČĎĚǦȞǨŇŘŤǎčďěǧȟǩňřť
##			Greek .....................: ΞφψΩϠδλμϟ                       Too wide, ambiguous, or ugly: ΔΘΛϕθϢϪπϡϣϫϖ
##			Cyrillic ..................: ЋДЖЯѢѦѪѮджфяѣѧѫѯ҂ՃՊՖ
##			    Useful ................: ЋЖЯѢф҂
##			turned ....................: Ʌɐǝʞɹʇʌʎ
##			inverted ..................: ¡¿ʁ
##			Currency ..................: ¢ ¥ ₤ ₸
##			Korean ....................: ㅈ ㅊ ㅍ ㅎ ㅠ ㅱ ㅸ ㅿ
##			Japanese ..................: ソッゞぅぇォゲサじすスせちづでネビべぺまミもモゟヲ
##			Technical .................: ⌲ ⍋ ⍒ ⍢ ⍤ ⍩
##			Shapes ....................: ◂ ▸ ▵ ▿
##			Misc ......................: ⁑ ⋆ ⍣ ʉ ʬ
##			People ....................: 웃 유
##			Math ......................: ≠ ≈ ‡ ± ∞ ∮
## 			Fractions .................: ½ ⅓ ⅔ ¼ ¾ ⅕ ⅖ ⅗ ⅘ ⅙ ⅚ ⅛ ⅜ ⅝ ⅞
## 			Fractions, small to big ...: ⅛ ⅙ ⅕ ¼ ⅓ ⅜ ⅖ ½ ⅗ ⅝ ⅔ ¾ ⅘ ⅚ ⅞
##			Alchemy ...................: 🜌 🜣 🜥 🜿 🝅
##			Runes .....................: ᚠ ᚤ ᚧ ᚬ ᚼ ᛎ ᛏ ᛘ ᛝ ᛦ ᛨ ᛬ ᛯ
##			All, sorted ...............: 웃유~±᛬‡⁑∞∮≈≠⋆⌲⍋⍒⍢⍣⍤⍩▵▸▿◂🜌🜣🜥🜿🝅¢¥₤₸½⅓¼⅕⅙⅛⅔⅖¾⅗⅜⅘⅚⅝⅞ʞʉʬλᚠᚤᚧᚬᚼᛎᛏᛘᛯᛝᛦᛨㅈㅊㅍㅎㅱㅸㅿㅠソッぺミゟ
##			All v1, by desired usage ..: ʞ λ ± ‡ ⁑ ∞ ∮ ~ ≈ ≠ ᛎ ᛏ ᛘ ᛯ ᛝ ᛦ ᛨ ᚠ ᚧ ᚬ ᚼ 🜣 🜥 🜿 🝅 ▵ ▸ ▿ ◂ ⍣ ⍤ ⍩ ⌲ ⍋ ⍒ ⍢ ¢ ¥ ₤ ₸ ᛬ 웃 유 ㅈ ㅊ ㅍ ㅎ ㅱ ㅸ ㅠ ソ ッ ゞ ぅ ぇ ォ ゲ サ じ す ス せ ち づ で ネ ビ べ ぺ ま ミ も モ ゟ ヲ ½ ⅓ ⅔ ¼ ¾ ⅕ ⅖ ⅗ ⅘ ⅙ ⅚ ⅛ ⅜ ⅝ ⅞
##			All v2, by desired usage (URL-safe, filesystem-safe, CLI-safe, programmer-friendly)
##				Wordsafe ..............: 0 1 2 3 4 5 6 7 8 9 C F G H J M P Q R V W X c f g h j m p q r v w x ʞ λ μ ᛎ ᛏ ᛘ ᛯ ᛝ ᛦ ᛨ ᚠ ᚧ ᚬ ᚼ 🜣 🜥 🜿 🝅 ▵ ▸ ▿ ◂ ҂ ‡ ± ⁑ ÷ ∞ ≈ ≠ Ω Ʊ Ξ ψ Ϡ δ ϟ Ћ Ж Я Ѣ ф ¢ £ ¥ § ¿ ɤ ʬ ⍤ ⍩ ⌲ ⍋ ⍒ ⍢ Â Ĉ Ê Ĝ Ĥ Ĵ Ŝ Ŵ Ŷ â ĉ ê ĝ ĥ ĵ ŝ ŵ ŷ Ã Ẽ Ñ Ỹ ã ẽ ñ ỹ Ä Ë Ẅ Ẍ Ÿ ä ë ẅ ẍ ÿ Á Ć É Ǵ Ń Ŕ Ẃ Ý á ć é ǵ ń ŕ ẃ ý Ǎ Č Ď Ě Ǧ Ȟ Ǩ Ň Ř Ť ǎ č ď ě ǧ ȟ ǩ ň ř ť ǝ ɹ ʇ ʌ ₸ ᛬ 웃 유 ㅈ ㅊ ㅍ ㅎ ㅱ ㅸ ㅠ ソ ッ ゞ ぅ ぇ ォ ゲ サ じ す ス せ ち づ で ネ ビ べ ぺ ま モ ゟ ヲ
##				Not wordsafe ..........: 0 1 2 3 4 5 6 7 8 9 A B C D E F G H I J K L M N O P Q R S T U V W X Y Z a b c d e f g h i j k l m n o p q r s t u v w x y z ʞ λ μ ᛎ ᛏ ᛘ ᛯ ᛝ ᛦ ᛨ ᚠ ᚧ ᚬ ᚼ 🜣 🜥 🜿 🝅 ▵ ▸ ▿ ◂ ҂ ‡ ± ⁑ ÷ ∞ ≈ ≠ Ω Ʊ Ξ ψ Ϡ δ ϟ Ћ Ж Я Ѣ ф ¢ £ ¥ § ¿ ɤ ʬ ⍤ ⍩ ⌲ ⍋ ⍒ ⍢ Â Ĉ Ê Ĝ Ĥ Î Ĵ Ô Ŝ Û Ŵ Ŷ Ẑ â ĉ ê ĝ ĥ î ĵ ô ŝ û ŵ ŷ ẑ Ã Ẽ Ĩ Ñ Õ Ũ Ỹ ã ẽ ĩ ñ õ ũ ỹ Ä Ë Ï Ö Ü Ẅ Ẍ Ÿ ä ë ï ö ü ẅ ẍ ÿ Á Ć É Ǵ Í Ń Ó Ŕ Ś Ú Ẃ Ý Ź á ć é ǵ í ń ó ŕ ś ú ẃ ý ź Ā Ē Ī Ō Ū Ȳ ā ē ī ō ū ȳ Ǎ Č Ď Ě Ǧ Ȟ Ǩ Ň Ǒ Ř Š Ǔ ǎ č ď ě ǧ ȟ ǩ ň ǒ ř š ǔ ǝ ɹ ʇ ʌ ₸ ᛬ 웃 유 ㅈ ㅊ ㅍ ㅎ ㅱ ㅸ ㅠ ソ ッ ゞ ぅ ぇ ォ ゲ サ じ す ス せ ち づ で ネ ビ べ ぺ ま モ ゟ ヲ ½ ⅓ ⅔ ¼ ¾ ⅕ ⅖ ⅗ ⅘ ⅙ ⅚ ⅛ ⅜ ⅝ ⅞
##			All v3 - v2 but machine-sorted by LC_ALL=C or LC_ALL=C.UTF-8; Note that not even standard bases sort property by this method, so this isn't really necessary.
##				Wordsafe ..............: 웃 유 § ± ¿ ÷ ҂ ᛬ ‡ ⁑ ∞ ≈ ≠ ⌲ ⍋ ⍒ ⍢ ⍤ ⍩ ▵ ▸ ▿ ◂ 🜣 🜥 🜿 🝅 ゞ ¢ £ ¥ ₸ 0 1 2 3 4 5 6 7 8 9 á Á â Â ǎ Ǎ ä Ä ã Ã c C ć Ć ĉ Ĉ č Č ď Ď é É ê Ê ě Ě ë Ë ẽ Ẽ ǝ ɤ f F g G ǵ Ǵ ĝ Ĝ ǧ Ǧ h H ĥ Ĥ ȟ Ȟ j J ĵ Ĵ ǩ Ǩ ʞ m M ń Ń ň Ň ñ Ñ p P q Q r R ŕ Ŕ ř Ř ɹ ŝ Ŝ ť Ť ʇ Ʊ v V ʌ w W ẃ Ẃ ŵ Ŵ ẅ Ẅ x X ẍ Ẍ ý Ý ŷ Ŷ ÿ Ÿ ỹ Ỹ ʬ δ λ μ Ξ ϟ ψ Ω Ϡ Ж Ћ ф Ѣ Я ᚠ ᚧ ᚬ ᚼ ᛎ ᛏ ᛘ ᛯ ᛝ ᛦ ᛨ ㅈ ㅊ ㅍ ㅎ ㅱ ㅸ ㅠ ぅ ぇ ォ ゲ サ じ す ス せ ソ ち ッ づ で ネ ビ べ ぺ ま モ ゟ ヲ
##				Not wordsafe ..........: 웃 유 § ± ¿ ÷ ҂ ᛬ ‡ ⁑ ∞ ≈ ≠ ⌲ ⍋ ⍒ ⍢ ⍤ ⍩ ▵ ▸ ▿ ◂ 🜣 🜥 🜿 🝅 ゞ ¢ £ ¥ ₸ 0 1 ½ ⅓ ¼ ⅕ ⅙ ⅛ 2 ⅔ ⅖ 3 ¾ ⅗ ⅜ 4 ⅘ 5 ⅚ ⅝ 6 7 ⅞ 8 9 a A á Á â Â ǎ Ǎ ä Ä ã Ã ā Ā b B c C ć Ć ĉ Ĉ č Č d D ď Ď e E é É ê Ê ě Ě ë Ë ẽ Ẽ ē Ē ǝ ɤ f F g G ǵ Ǵ ĝ Ĝ ǧ Ǧ h H ĥ Ĥ ȟ Ȟ i I í Í î Î ï Ï ĩ Ĩ ī Ī j J ĵ Ĵ k K ǩ Ǩ ʞ l L m M n N ń Ń ň Ň ñ Ñ o O ó Ó ô Ô ǒ Ǒ ö Ö õ Õ ō Ō p P q Q r R ŕ Ŕ ř Ř ɹ s S ś Ś ŝ Ŝ š Š t T ʇ u U ú Ú û Û ǔ Ǔ ü Ü ũ Ũ ū Ū Ʊ v V ʌ w W ẃ Ẃ ŵ Ŵ ẅ Ẅ x X ẍ Ẍ y Y ý Ý ŷ Ŷ ÿ Ÿ ỹ Ỹ ȳ Ȳ z Z ź Ź ẑ Ẑ ʬ δ λ μ Ξ ϟ ψ Ω Ϡ Ж Ћ ф Ѣ Я ᚠ ᚧ ᚬ ᚼ ᛎ ᛏ ᛘ ᛯ ᛝ ᛦ ᛨ ㅈ ㅊ ㅍ ㅎ ㅱ ㅸ ㅠ ぅ ぇ ォ ゲ サ じ す ス せ ソ ち ッ づ で ネ ビ べ ぺ ま モ ゟ ヲ
##				48j1 .................: ± ҂ ‡ ⁑ ▵ ▸ ▿ ◂ 🜣 🜥 🜿 🝅 0 1 2 3 4 5 6 7 8 9 c f g h j ʞ m p q r v w x λ μ ᚠ ᚧ ᚬ ᚼ ᛎ ᛏ ᛘ ᛯ ᛝ ᛦ ᛨ
##				64j1u ................: 0 1 2 3 4 5 6 7 8 9 a A b B c C d D e E f F g G h H i I j J k K ʞ l L m M n N o O p P q Q r R s S t T u U v V w W x X y Y z Z λ
##				64j1w ...............: ± ÷ ҂ ‡ ⁑ ∞ ≈ ≠ ▵ ▸ ▿ ◂ 🜣 🜥 🜿 🝅 0 1 2 3 4 5 6 7 8 9 c C f F g G h H j J ʞ m M p P q Q r R v V w W x X λ μ ᚠ ᚧ ᚬ ᚼ ᛎ ᛏ ᛘ ᛯ ᛝ ᛦ ᛨ
##				128j1 ................: § ± ¿ ÷ ҂ ‡ ⁑ ∞ ≈ ≠ ⌲ ⍋ ⍒ ⍢ ⍤ ⍩ ▵ ▸ ▿ ◂ 🜣 🜥 🜿 🝅 ¢ £ ¥ 0 1 2 3 4 5 6 7 8 9 Á â Â ä Ä ã Ã c C Ć ĉ Ĉ É ê Ê ë Ë ẽ Ẽ ɤ f F g G ĝ Ĝ h H ĥ Ĥ j J ĵ Ĵ ʞ m M ñ Ñ p P q Q r R ŝ Ŝ Ʊ v V w W ŵ Ŵ ẅ Ẅ x X ẍ Ẍ ŷ Ŷ ÿ Ÿ ỹ Ỹ ʬ δ λ μ Ξ ϟ ψ Ω Ϡ Ж Ћ ф Ѣ Я ᚠ ᚧ ᚬ ᚼ ᛎ ᛏ ᛘ ᛯ ᛝ ᛦ ᛨ
##				256j1 ................: 웃 유 § ± ¿ ÷ ҂ ᛬ ‡ ⁑ ∞ ≈ ≠ ⌲ ⍋ ⍒ ⍢ ⍤ ⍩ ▵ ▸ ▿ ◂ 🜣 🜥 🜿 🝅 ゞ ¢ £ ¥ ₸ 0 1 2 3 4 5 6 7 8 9 a A á Á â Â ǎ Ǎ ä Ä ã Ã ā Ā b B c C ć Ć ĉ Ĉ č Č d D ď Ď e E é É ê Ê ě Ě ë Ë ẽ Ẽ ē Ē ǝ ɤ f F g G ǵ Ǵ ĝ Ĝ ǧ Ǧ h H ĥ Ĥ ȟ Ȟ i I í Í î Î ï Ï ĩ Ĩ ī Ī j J ĵ Ĵ k K ǩ Ǩ ʞ l L m M n N ń Ń ň Ň ñ Ñ o O ó Ó ô Ô ǒ Ǒ ö Ö õ Õ ō Ō p P q Q r R ŕ Ŕ ř Ř ɹ s S ś Ś ŝ Ŝ š Š t T ʇ u U ú Ú û Û ǔ Ǔ ü Ü ũ Ũ ū Ū Ʊ v V ʌ w W ẃ Ẃ ŵ Ŵ ẅ Ẅ x X ẍ Ẍ y Y ý Ý ŷ Ŷ ÿ Ÿ ỹ Ỹ ȳ Ȳ z Z ź Ź ẑ Ẑ ʬ δ λ μ Ξ ϟ ψ Ω Ϡ Ж Ћ ф Ѣ Я ᚠ ᚧ ᚬ ᚼ ᛎ ᛏ ᛘ ᛯ ᛝ ᛦ ᛨ ㅈ ㅊ ㅍ ㅎ ㅱ ㅸ ㅠ ぅ ぇ ォ ソ ッ
##		Not OK
##			Standard
##				Bad for filesystems ...:   "             *         / :   <   > ?     \           |
##				Bad for internet ......:     $   &         + ,     / : ;   =   ? @
##				Bad for programmers ...: ! " $ % & ' ( ) * + , - . / : ; < = > ? @ [ \ ] ^ _ ` { | } ~
## 			Fractions
##				Don't fit .............: ↉ ⅐ ⅑ ⅒
##			Misc don't fit [sorted] ...: 🯅⌁★☜☝☞☟☢☣☤☮☯☻♚♛♞♠♣♥♦♫⚓⚖⛁⛈ⒸⒹⒻⒼⒽⒿⓀⓂⓃⓅⓆⓇⓉⓋⓌⓍⓎⓒⓓⓕⓖⓗⓙⓚⓜⓝⓟⓠⓡⓣⓥⓦⓧⓨϠѰ


##	History:
##		- 20230830 JC: Created from x9bsnaps as template.
##		- 20230901-0920 JC: Added bases and polished 'j1' character sets.
##		- 20230924 JC: Bug fix, inability to --lcase base 26.
##		- 20260411 JC: Removed base94ascii. There is some bug that puts filenames on the filesystem into the output. But it's not an important base to include.
##		- 20260417 JC:
##			- Removed a large amount of unused boilerplate, debugging, and profiling code that has been in here from day one.
##			- Allow switches to only have a single leading-dash, without complaining about invalid args.
##			- Remove some unnecessary code paths, such as arg-parser building a flat string of args.
